ldk/go/uiClient.go

Bugfix for when Loops are attempting to be gracefully shutdown, the global/searchbar on teardown were getting a fatal error: `bad access: nil dereference`
Found while debugging [SIDE-1021](https://crosschx.atlassian.net/browse/SIDE-1021)

fix for bad access: nil dereference

---

ldk/node/.eslintrc.js
ldk/node/dist/access.js
ldk/node/dist/brokerGrpcServer.d.ts
ldk/node/dist/brokerGrpcServer.js
ldk/node/dist/categories.js
ldk/node/dist/hostClients/fileSystemService.js
ldk/node/dist/hostClients/processService.js
ldk/node/dist/hostClients/whisperService.js
ldk/node/dist/hostClients/windowService.js
ldk/node/dist/logging.js
ldk/node/dist/operatingSystem.js
ldk/node/src/access.ts
ldk/node/src/brokerGrpcServer.ts
ldk/node/src/categories.ts
ldk/node/src/hostClients/fileSystemService.ts
ldk/node/src/hostClients/processService.ts
ldk/node/src/hostClients/whisperService.ts
ldk/node/src/hostClients/windowService.ts
ldk/node/src/logging.ts
ldk/node/src/operatingSystem.ts

This PR fixes a bug with our linting configuration that was generating false positives on the `no-shadow` rule. It turns out that that rule does not work with Typescript files, and we need to use the one from `@typescript-eslint` instead.
Also fixes minor linting complaints in `src/brokerGrpcServer.ts` file.

[SIDE-1045] Correct linting rule, remove unnecessary disables

---

ldk/go/filesystemClient.go

This PR fixes a bug with the Go LDK preventing the `GRPCFile.Close` function from completing on the client side.

[SIDE-1508] Unblock Close without waiting for stream to close

---

ldk/go/whisperClient.go

This PR adds comments to the WhisperClient funcs that they are blocking until the Whisper is dismissed.

[SIDE-1838] Add Blocking clarifications to client funcs

---

docs/src/components/menu/desktop-menu.tsx
docs/src/components/menu/menu.module.scss
docs/src/markdown-pages/troubleshooting.md
docs/src/pages/global.scss
docs/src/pages/index.scss

This PR:
- Adds a quick troubleshooting guide with some of the common troubleshooting steps and questions I've encountered so far.
- Adds the updated brand colours to the global styles file.
- Adds styles for the code blocks elements (both inline and block level)
- Used the dark purple gradient for the desktop menu.
- Adds a visual indicator for the current page.

[SIDE-1917] Add troubleshooting guide

---

docs/gatsby-config.js

use root path for assets since we're moving to a custom domain with content at the root

SIDE-2090: update gatsby config to support custom domain

---

docs/static/CNAME

oliveai.dev keeps resetting custom domain on deployments of the docs to olive-helps github pages.
Add CNAME file with oliveai.dev so that deployments don't remove the custom domain setting from the olive-helps github page. Adding the CNAME file to the static directory means the docs build process automatically copies it to the root directory (which is where github needs it to be).

SIDE-2138: add CNAME file with oliveai.dev

---

ldk/javascript/examples/javascript-loop/package.json
ldk/javascript/examples/self-test-loop/webpack.config.js
ldk/javascript/examples/typescript-loop/package.json
ldk/javascript/package-lock.json
ldk/javascript/package.json
ldk/javascript/readme.md
ldk/javascript/src/index.ts
ldk/javascript/src/webpack/config.ts

This PR does a number of things:
- Updates the way that we polyfill modern capabilities into the environment so that the user doesn't need to add incrementally new polyfills (like `Symbol.asyncIterator`) as they add more features. This comes at the cost of an increased compilation size.
- Removes the `core-js` entries from the config.
- Uses Babel to transpile TS too.

[SIDE-2123] Fix Runtime Polyfills

---

ldk/javascript/src/types/oliveHelps/index.d.ts
ldk/javascript/src/whisper/index.ts
ldk/javascript/src/whisper/whisper.test.ts

Passing the whisper object back with all component callbacks will allow loop authors to utilize the `close` and eventually the `update` methods inside of the components callbacks.
Note: This PR also removes the `all` method from the whisper service.  The `all` method was left over from the thinking that whispers would have to be persisted through a loop shut down. 
- Also add an error parameter to the close method on the whisper object

SIDE-2160: Whisper Return Object in all Component Callbacks 

---

docs/src/markdown-pages/guides/submitting-loop.md

The link for "becoming a Loop author" was broken. This should fix it.

SIDE-2130b: updated getting started link

---

ldk/go/keyboardService.go
ldk/go/keyboardService_test.go

This PR:
- Reworks the Hotkey matching logic so that it prevents matches when the actual keypress is a superset of the requested keypress.
- Adds some tests to validate the above.

[SIDE-2236] Fix hotkey matching logic

---

ldk/javascript/src/webpack/generate-banner.test.ts
ldk/javascript/src/webpack/generate-banner.ts

Previously, if package.json did not include an "LDK" key a  TypeError: Cannot convert undefined or null to object would be thrown.

Fix issue where permissions error not thrown

---

ldk/javascript/examples/self-test-loop/package.json
ldk/javascript/examples/self-test-loop/src/selfTest.ts
ldk/javascript/examples/self-test-loop/src/tests/index.ts
ldk/javascript/package-lock.json

We noticed that directory exists was not working properly a few days ago, in my investigation, I added a new self-test around the existence of a directory to investigate.
Upon updating to the latest sidekick, I see that a fix had already been made to the production code there. (versions of OH > OH > v0.17.3)
I have a testing counterpart PR opened with sidekick that can be reviewed separately.

SIDE-2273: Adding self-test for directory exists on the filesystem

---

ldk/javascript/examples/self-test-loop/src/tests/index.ts

This PR in the LDK simply adds a visual test for checkbox and radio whisper types to self-test-loop. Support for markdown is added via sidekick in another PR.

SIDE-2212: Support markdown for checkbox and radio components

---

ldk/javascript/package.json
ldk/javascript/src/webpack/shared.ts

This fixes an issue introduced in 3.0.1 where the Webpack config used for Loop compilation was not appropriately converting ES6 code from the LDK to ES5 for use by Helps.

HELPS-758: Run Webpack against node_modules and update LDK to 3.0.2

---

docs/src/markdown-pages/aptitudes/whisper.create.md
ldk/javascript/examples/self-test-loop/src/tests/whisper/whisper-update.ts
ldk/javascript/src/types/oliveHelps/index.d.ts
ldk/javascript/src/webpack/generate-banner.test.ts
ldk/javascript/src/webpack/generate-banner.ts
ldk/javascript/src/whisper/mapper.ts
ldk/javascript/src/whisper/types.ts
ldk/javascript/src/whisper/whisper.test.ts

This PR:
- Adds the `key` property to all Whispers for both the internal and external Whisper types.
- Updates the self test loop to test for whisper update changes.
- Adds documentation appropriate for the above.
- Increments the OH contract version.

[SIDE-2544] Add Whisper Key properties

---

docs/src/markdown-pages/aptitudes/filesystem.md
ldk/javascript/readme.md

This PR:
- Adds that permissions to the working directory are automatically granted and only an empty object needs to be provided.
- Reworks some of the aptitude documentation and adds some path glob examples.

[HELPS-775] Update documentation about relative file paths

---

docs/src/markdown-pages/aptitudes/user.createJWT.md
ldk/javascript/examples/self-test-loop/src/config/user-group.ts
ldk/javascript/examples/self-test-loop/src/tests/user/index.ts
ldk/javascript/src/promisify.ts
ldk/javascript/src/types/oliveHelps/index.d.ts
ldk/javascript/src/user/index.ts
ldk/javascript/src/user/user.test.ts

This commit adds an optional includeEmail parameter to the User Aptitude
jwt function. When this parameter is set to true, the JWT will include
the current user's email address. When the parameter is unset, or false,
the email address will not be included in the JWT's claims, limiting
potential PII exposure.

HELPS-788: Omit unnecessary claims from User Aptitude JWT

---

ldk/javascript/examples/self-test-loop/src/config/network-group.ts
ldk/javascript/examples/self-test-loop/src/config/system-group.ts
ldk/javascript/examples/self-test-loop/src/tests/network/index.ts
ldk/javascript/examples/self-test-loop/src/tests/system/index.ts

Adding selfTestLoop to test httpRequest blocking behavior. The test will fail if httpRequest block the thread. This issue is resolved in the sidekick.

Helps 898 http request blocks

---

ldk/javascript/examples/self-test-loop/src/config/whisper-group.ts
ldk/javascript/examples/self-test-loop/src/selfTest.ts
ldk/javascript/examples/self-test-loop/src/testingFixtures/testWhisper.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/src/types/oliveHelps/index.d.ts
ldk/javascript/src/whisper/types.ts

This PR updates the types for the onDrop callbacks, and allows Loop Authors to clear and/or re-arrange files from the selected list.

[HELPS-854] Update Dropzone event types, support setting/clearing values.

---

docs/src/markdown-pages/guides/permissions-configuration.md
ldk/javascript/readme.md
ldk/javascript/src/webpack/config.ts
ldk/javascript/src/webpack/generate-ldk-settings.test.ts
ldk/javascript/src/webpack/generate-ldk-settings.ts

This commit adds configurable LDK permissions via an optional config
file and LDK_CONFIG env variable which can be set during the Webpack
build.
The commit adds new Webpack configuration in support of this change,
along with testing and documentation changes.

HELPS-829: Enable per environment LDK permissions

---

ldk/javascript/examples/self-test-loop/package.json
ldk/javascript/examples/self-test-loop/src/config/user-group.ts
ldk/javascript/examples/self-test-loop/src/tests/user/index.ts

This commit adds a test to the self test loop for exercising the JWT call when called with `{includeEmail: false}`.

Exclude email self test

---

ldk/javascript/examples/self-test-loop/src/tests/whisper/whisper-update.ts
ldk/javascript/src/webpack/generate-banner.test.ts

This PR adds a test for setting the text input to an emptry string and confirming that the input's contents are cleared.
Tests fix for #359.

[HELPS-1579] Add test for setting text input to empty string

---

ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts

Update error message character limit accordingly in RichText Editor test loop.

HELPS-778 Update error message char limit to 50

---

extension/chrome/background.js
extension/chrome/manifest.json
extension/firefox/background.js

Service workers do not stay alive with their socket connections.
Long term, we will have to come up with a work-around.

Revert Chrome Extension to Manifest V2

---

ldk/javascript/src/webpack/generate-banner.test.ts
ldk/javascript/src/webpack/generate-banner.ts
ldk/javascript/src/webpack/ldk-settings.ts

https://crosschx.atlassian.net/browse/HELPS-2018
For the public who can't see our Jira tickets: this is adding aptitude permissions in the webpack config for the upcoming Screen aptitude

Helps 2018 screen aptitude permission

---

ldk/javascript/examples/self-test-loop/src/config/screen-group.ts
ldk/javascript/examples/self-test-loop/src/tests/screen/hashTests.ts
ldk/javascript/examples/self-test-loop/src/tests/screen/index.ts
ldk/javascript/src/promisify.ts
ldk/javascript/src/screen/index.ts
ldk/javascript/src/screen/screen.test.ts
ldk/javascript/src/screen/types.ts
ldk/javascript/src/types/oliveHelps/common.d.ts
ldk/javascript/src/types/oliveHelps/screen.d.ts

Added support for listen*Hash, comparehash, and *hash (where * = average, difference, perception), as well as listenPixelDiff and listenPixelActiveWindow

Helps 2614 ocr experimental screen detection methods

---

ldk/javascript/package-lock.json
ldk/javascript/src/whisper/react/readme.md
ldk/javascript/src/whisper/react/renderer-config.ts
ldk/javascript/src/whisper/react/renderer.test.tsx
ldk/javascript/src/whisper/react/renderer.ts
ldk/javascript/src/whisper/react/whisper-instance-wrapper.ts
ldk/javascript/src/whisper/react/whisper-render-instance.ts
package-lock.json

Fixes #473
Added a way for whisper render instances to track and call an internal close handler (used for unmounting stuff) and an external on close handler (for the end user to use).
If you check my previous commit it used a different approach, I think this one is better though.
I also question that `render` and `renderNewWhisper` should take a ReactNode, I think `ReactElement` would be more accurate since the top level component does need to be a `ReactElement`.

HELPS-2776 onClose is not called for react whispers

---

ldk/javascript/examples/self-test-loop/package.json
ldk/javascript/examples/self-test-loop/src/config/user-group.ts

When running the "User Aptitude - JWT - Email Claim" test, the test initiates, but then freezes and never completes.
It turns out that we need to add the `optionalClaims` and add the email address to it.
The permission for user in `package.json` should be like this: 
```
"user": {
"optionalClaims": [
{          
"value": "email"
}
]
},
```

HELPS-2529-  Update "User Aptitude - JWT - Email Claim" test package.json

---

ldk/javascript/examples/self-test-loop/src/config/whisper-group.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/utils.ts
ldk/javascript/src/types/oliveHelps/whisper.d.ts
ldk/javascript/src/whisper/types.ts

- Fixes a type error with `filterOptions.stringify` to make it inline with OH.
- Adds a test to self test loop to excercise `filteerOptions`
- Modifies FilterOption.value to be `any` rather than `string`

HELPS-3058 Change stringify to be an array of strings

---

ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/src/types/oliveHelps/whisper.d.ts
ldk/javascript/src/whisper/types.ts

- Add ability to change the display text stating that 
1. the the file not being accepted
2. the area that user drops a file
3.  browse a file
4.  has reached the maximum number of files.

Helps 2930 Customize DropZone component text

---

ldk/javascript/examples/self-test-loop/src/config/screen-group.ts
ldk/javascript/examples/self-test-loop/src/tests/screen/index.ts
ldk/javascript/src/screen/index.ts
ldk/javascript/src/screen/screen.test.ts
ldk/javascript/src/screen/types.ts
ldk/javascript/src/types/oliveHelps/screen.d.ts

- Implement new exposed method for loop author to listen to ocr monitor 
- This will listen to active window changes
- This function provides active window recognition in the backend
- Users can run multiple `listenOcrMonitor` function at the same time to get better ocr accuracy.

Helps 3411 listenOcrMonitor

---

ldk/javascript/src/network/mapper.ts
ldk/javascript/src/network/network.test.ts
ldk/javascript/src/whisper/index.ts

- Add return statement after rejecting a promise to stop function execution
- Add test cases for network websocket

HELPS-4347 return after reject

---

ldk/javascript/examples/self-test-loop/src/tests/screen/index.ts
ldk/javascript/src/document/document.test.ts
ldk/javascript/src/screen/screen.test.ts
ldk/javascript/src/screen/types.ts
ldk/javascript/src/types/oliveHelps/screen.d.ts

- Updated ocrResult's prop `conf` to `confidence`. 
- Updated Self Test Loop accordingly.

Helps- 4624 Changed `conf` to `confidence`

---

ldk/javascript/examples/self-test-loop/src/tests/user/index.ts
ldk/javascript/src/types/oliveHelps/user.d.ts
ldk/javascript/src/user/index.ts
ldk/javascript/src/user/user.test.ts

- Added `email` to `jwtWithUserDetails`
- Updated test accordingly

Helps-4640 Added email to jwtWithUserDetails and updated test
