ldk/csharp/OliveHelpsLDK/OliveHelpsLDK/OliveHelpsLDK.csproj
ldk/node/package.json

Version number bump to 2.0.0-alpha

[SIDE-1153] Publish 2.0.0-alpha

---

ldk/csharp/OliveHelpsLDK/Example/Program.cs
ldk/csharp/OliveHelpsLDK/OliveHelpsLDK/IStreamingCall.cs
ldk/csharp/OliveHelpsLDK/OliveHelpsLDK/OliveHelpsLDK.csproj
ldk/csharp/OliveHelpsLDK/OliveHelpsLDK/StreamingCall.cs

Adds support for consuming Streaming Calls as `IAsyncEnumerable`.

[SIDE-1091] Add support for IAsyncEnumerable

---

.github/workflows/nuget.yml
ldk/csharp/OliveHelpsLDK/OliveHelpsLDK/OliveHelpsLDK.csproj
ldk/node/package.json

This PR updates the metadata and adds a publication action on new releases
@iangallOlive could you create an API key in NuGet for the Olive organization and add it as a GitHub actions secret as `NUGET_API_KEY`.

[SIDE-1085] Publish LDK to NuGet

---

ldk/node/examples/clipboard/package.json
ldk/node/examples/clipboard/readme.md
ldk/node/examples/network/readme.md
ldk/node/examples/whisper-disambiguation/readme.md
ldk/node/examples/whisper-list/readme.md

The redundant parts of this can be collapsed if desired. However, for the moment, duplication doesn't seem too unwieldy.

update NodeJS examples to include relevant command

---

ldk/node/dist/hostClients/whisperMessageBuilder.d.ts
ldk/node/dist/hostClients/whisperMessageBuilder.js
ldk/node/src/hostClients/whisperMessageBuilder.ts

Meta data wasn't being passed correctly, so when the whisper server would try to access it, it would cause a seg fault

SIDE-1510 Fix ConfirmationWhisper in Node

---

ldk/goja/.eslintignore
ldk/goja/package-lock.json
ldk/goja/package.json
ldk/goja/readme.md
ldk/goja/src/webpack/config.ts
ldk/goja/src/webpack/generate-banner.ts
ldk/goja/tests/default-with-config/.babelrc
ldk/goja/tests/default-with-config/index.js
ldk/goja/tests/default-with-config/package-lock.json
ldk/goja/tests/default-with-config/package.json
ldk/goja/tests/default-with-config/webpack.config.js
ldk/goja/tests/default/index.js
ldk/goja/tests/default/index.ts
ldk/goja/tests/default/package-lock.json
ldk/goja/tests/default/package.json
ldk/goja/tests/default/tsconfig.json
ldk/goja/tsconfig.json

Add default webpack configuration and examples.
- Includes pure command line reference example.
- Includes webpack merge example.
- Includes TS support.
- Includes Goja readme updates.

[SIDE-2033] Add Webpack configuration

---

.github/workflows/docs.yml

In order to display images properly @ https://open-olive.github.io/loop-development-kit/ldk/javascript/
the image asset directory needed to also be sent with our documentation.

Side 2122b doc images

---

ldk/javascript/examples/self-test-loop/src/selfTest.ts
ldk/javascript/examples/self-test-loop/src/tests/index.ts

Setting `selected` attribute on Select and Radio whisper types changes default value.

SIDE-2172: Add self-test-loop coverage for selected attribute for text input and radio buttons

---

ldk/javascript/src/webpack/generate-banner.test.ts
ldk/javascript/src/webpack/generate-banner.ts

This PR renames `ldkVersion` -> `oliveHelpsContractVersion `

SIDE-2133 rename semver

---

ldk/javascript/src/clipboard/clipboard.test.ts
ldk/javascript/src/cursor/cursor.test.ts
ldk/javascript/src/filesystem/filesystem.test.ts
ldk/javascript/src/keyboard/keyboard.test.ts
ldk/javascript/src/network/network.test.ts
ldk/javascript/src/process/process.test.ts
ldk/javascript/src/promisify.ts
ldk/javascript/src/types/oliveHelps/index.d.ts
ldk/javascript/src/ui/ui.test.ts
ldk/javascript/src/vault/vault.test.ts
ldk/javascript/src/whisper/whisper.test.ts
ldk/javascript/src/window/window.test.ts

This PR adds error handling to the listener functions.
TODO:

[SIDE-2092] Add error handling for listeners

---

ldk/javascript/src/types/oliveHelps/index.d.ts
ldk/javascript/src/whisper/index.ts
ldk/javascript/src/whisper/whisper.test.ts

This PR updates the Whisper handler function signatures with the error object that may be provided if there's a failure encountered.

[SIDE-2258] Update Whisper signatures

---

docs/src/markdown-pages/aptitudes/window.listen-active-window.md

This PR explains what active window changes are filtered out.

[SIDE-2228] Add statement about Listen Active Window filtering

---

ldk/javascript/package.json
ldk/javascript/src/webpack/generate-banner.test.ts
ldk/javascript/src/webpack/generate-banner.ts

Version Bump - 3.0.0-beta.4

---

ldk/javascript/package.json

This PR updates the package version to 3.0.0.

[SIDE-2426] Update to v3.0.0

---

docs/src/markdown-pages/aptitudes/whisper.create.md
ldk/javascript/examples/self-test-loop/src/selfTest.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper-update.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper.ts
ldk/javascript/src/whisper/index.ts
ldk/javascript/src/whisper/mapper.test.ts
ldk/javascript/src/whisper/mapper.ts
ldk/javascript/src/whisper/types.ts
ldk/javascript/src/whisper/whisper.test.ts

This PR:
- keeps track of values changing for whisper embedded form components
- sends component state back as `componentState` on whisper
- allows for multi-whisper component state

SIDE: 2143 component state

---

ldk/javascript/examples/self-test-loop/src/selfTest.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/src/types/oliveHelps/index.d.ts
ldk/javascript/src/whisper/types.ts

Adds an optional onFocus callback to the following Whisper Components:
* TextInput
* NumberInput
* Email
* Telephone
* Password

HELPS-325: Add onFocus property to Input whispers

---

docs/src/markdown-pages/guides/troubleshooting.md

Updated documentation, indicating that adding Polyfills should be avoided or it could cause problems.
This is the link of the task: https://crosschx.atlassian.net/browse/SIDE-2269

SIDE-2269 Updated Check For Polyfills

---

ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts

This is for UI testing purpose

Helps 221 header sizes testing

---

ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts

Divider and Markdown have been added for CollapseBox and Divider format UI validation.

Added markdown&divider to test collapsebox&divider

---

ldk/javascript/examples/self-test-loop/src/config/index.ts
ldk/javascript/examples/self-test-loop/src/config/whisper-validation-group.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/utils.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/validation/componentIds.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/validation/index.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/whisper-validation.ts
ldk/javascript/examples/self-test-loop/webpack.config.js
ldk/javascript/src/types/oliveHelps/index.d.ts
ldk/javascript/src/whisper/mapper.test.ts
ldk/javascript/src/whisper/types.ts

I added input-able and select-able components validation

Helps 132 components validation

---

ldk/javascript/src/types/oliveHelps/index.d.ts
ldk/javascript/src/whisper/mapper.ts
ldk/javascript/src/whisper/types.ts

This PR adds the dropzone component.

[HELPS-853] Add Dropzone Component

---

docs/src/markdown-pages/aptitudes/user.createJWT.md

This PR adds some information about upcoming changes to the default behavior of the User Aptitude to its Dev Hub doc page.

HELPS-788: Update docs with deprecation information

---

ldk/javascript/examples/self-test-loop/src/config/whisper-group.ts
ldk/javascript/examples/self-test-loop/src/testingFixtures/testWhisper.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/utils.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/whisper-update.ts
ldk/javascript/src/types/oliveHelps/index.d.ts
ldk/javascript/src/whisper/mapper.ts
ldk/javascript/src/whisper/types.ts

In addition to that
- addressed tech debt around how the JustifyContent names were being used (added FlexStart and FlexEnd). 
- Alphabetized. 
- Changed all incorrect JustifyContent properties to something that actually corresponded with a property. The default property was "SpaceBetween", and "SpaceAround" and "SpaceEvenly" weren't actually doing anything.

HELPS-937 Add the AlignItems property to Box components.

---

ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/utils.ts

This PR fixes a bug in the Dropzone test where the test Whisper was being closed too early.

[HELPS-1316] Fix dropzone test bug

---

ldk/javascript/package.json

[HELPS-1513] Update version number

---

ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts

This PR fixes the dropzone test so that we don't close the Whisper before we get feedback from the user.

[HELPS-1605] Fix Whisper dropzone test bug

---

extension/chrome/manifest.json
extension/firefox/manifest.json

Bumping extension version to 0.2

bump browser extension version

---

ldk/javascript/src/webpack/generate-banner.test.ts
ldk/javascript/src/webpack/generate-banner.ts

Increment oliveHelpsContractVersion to 0.1.7 for the incoming screen aptitude.

increment oliveHelpsContractVersion to 0.1.7

---

ldk/javascript/examples/self-test-loop/src/config/whisper-group.ts
ldk/javascript/examples/self-test-loop/src/config/whisper-update-group.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/whisper-update.tsx
ldk/javascript/src/types/oliveHelps/whisper.d.ts
ldk/javascript/src/whisper/mapper.ts
ldk/javascript/src/whisper/react/component-handlers.ts
ldk/javascript/src/whisper/react/component-types.ts
ldk/javascript/src/whisper/types.ts

Added support for breadcrumb component & updated self test loop

[HELPS-2394] Added breadcrumb component and updated self test loop

---

ldk/javascript/examples/self-test-loop/src/tests/screen/index.ts

If we filter out lower conv results, there's no value returned. So I deleted the filter function so that QA can see some results there first. Will figure out what happened there.

updated ocr test

---

ldk/javascript/examples/fetch/fetch-polyfill.js
ldk/javascript/examples/fetch/index.js
ldk/javascript/examples/fetch/package-lock.json
ldk/javascript/examples/fetch/package.json

This is an example as to how you can polyfill fetch with the ldk. This may be useful if you use extra libraries that depend on WHATWG's fetch Api.

[HELPS-2404] Fetch polyfill example.

---

ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts

Update test for section title sample

udpate test for documentation

---

ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/src/types/oliveHelps/whisper.d.ts
ldk/javascript/src/whisper/types.ts

- Add `disabled` property to Icon
- Add test to self test loop

HELPS-3673 Add disabled state to Icon, and self test

---

ldk/javascript/examples/self-test-loop/src/config/whisper-group.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/src/types/oliveHelps/whisper.d.ts
ldk/javascript/src/whisper/mapper.ts
ldk/javascript/src/whisper/react/component-handlers.ts
ldk/javascript/src/whisper/react/component-types.ts
ldk/javascript/src/whisper/types.ts

- added component Typography 
- added tooltip property also was not in the ticket, but change was make to UI to include tooltip [HERE](https://gitlab.oliveai.com/oliveai/platform/desktop/ui/-/blob/main/src/renderers/components/content/universal/views/typography/index.jsx#:~:text=tooltip%3A%20PropTypes.string%2C)

HELPS-3482 typography component

---

ldk/javascript/src/browser/browser.test.ts
ldk/javascript/src/browser/index.ts
ldk/javascript/src/types/oliveHelps/browser.d.ts

- Add `frameId` & `type` to NetworkActivityDetails

Helps 4130 nav details

---

ldk/javascript/examples/self-test-loop/package.json
ldk/javascript/examples/self-test-loop/src/config/browser-group.ts
ldk/javascript/examples/self-test-loop/src/tests/browser/index.ts
ldk/javascript/src/browser/browser.test.ts
ldk/javascript/src/browser/index.ts
ldk/javascript/src/types/oliveHelps/browser.d.ts

- Create TabChangeDetails interface
- Add listenTabChange function to browser interface
- add new Browser test to self test loop

Helps 4131 listen tab change

---

ldk/javascript/examples/self-test-loop/src/config/system-group.ts
ldk/javascript/examples/self-test-loop/src/tests/system/index.ts
ldk/javascript/src/system/index.ts
ldk/javascript/src/system/system.test.ts
ldk/javascript/src/types/oliveHelps/system.d.ts

- added method getEnvironment() to system aptitude
- added  new test to self test loop for getEnvironment 
- updated test for operatingSystem()
- added unit tests

added getEnvironment method to system aptitude

---

ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/whisper-update.tsx
ldk/javascript/src/whisper/mapper.ts
ldk/javascript/src/whisper/types.ts

- Deleted Deprecated Box component
- Updated  Self tests accordingly.

Helps 1804 remove deprecated box component

---

ldk/javascript/examples/self-test-loop/src/tests/browser/index.ts
ldk/javascript/src/browser/browser.test.ts
ldk/javascript/src/browser/index.ts
ldk/javascript/src/types/oliveHelps/browser.d.ts

- Add listenerType to UIElementArguments type definition

Helps 4211 UI listener type

---

ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/src/whisper/types.ts

Hot fix/typography typo

---

ldk/javascript/src/types/oliveHelps/whisper.d.ts

- typo varient to variant 
- removed string in type variant

HELPS-3482-hotfix-typo-variant 

---

ldk/javascript/examples/self-test-loop/src/tests/screen/index.ts
ldk/javascript/src/whisper/types.ts

- removed xAxisTimeSeries and yAxisTimeSeries from whisper/types.ts

remove x/yaxistimeseries properties

---

ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/src/types/oliveHelps/whisper.d.ts
ldk/javascript/src/webpack/CheckWarningsAndErrorsPlugin.ts
ldk/javascript/src/whisper/mapper.ts
ldk/javascript/src/whisper/types.ts

HELPS-1792 fix warning error grammer

---

ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/src/types/oliveHelps/whisper.d.ts
ldk/javascript/src/webpack/CheckWarningsAndErrorsPlugin.ts
ldk/javascript/src/whisper/mapper.ts
ldk/javascript/src/whisper/types.ts

Reverts open-olive/loop-development-kit#581

Revert "HELPS-1792 fix warning error grammer"

---

ldk/javascript/examples/self-test-loop/src/tests/browser/index.ts

- Update listenUIElement test so that it passes/fails correctly

HELPS-4650 fix browser listenUIElement self test

---

ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/src/types/oliveHelps/whisper.d.ts
ldk/javascript/src/whisper/types.ts

- added label prop to type Progress Component 
- added test to self test loop

Helps-4648 add label to progress component

---

ldk/javascript/examples/self-test-loop/src/config/ui-group.ts
ldk/javascript/examples/self-test-loop/src/config/whisper-group.ts
ldk/javascript/examples/self-test-loop/src/tests/whisper/index.ts
ldk/javascript/src/types/oliveHelps/whisper.d.ts
ldk/javascript/src/webpack/CheckWarningsAndErrorsPlugin.ts
ldk/javascript/src/whisper/types.ts

- Add `Height, MinHeight, MaxHeight` properties to Box component

Helps 4112 add dynamic height properties

---

examples/self-test-loop/src/tests/network/index.ts

update test order
